default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: ''
  timeout: 5000

development:
  <<: *default
  database: urlshort_development

test:
  <<: *default
  database: urlshort_test